import { SeasonalCategory } from ".";
import { TypeHidden, TypeState, TypeTags } from "../../munzee";

const s2020: SeasonalCategory[] = [
  {
    name: "20/20 Vision",
    id: "vision2020",
    starts: "2020-01-02T15:00:00-06:00",
    ends: "2020-12-31T23:59:00-06:00",
    specials: [
      {
        name: "Spectacular Spectacles",
        icon: "spectacularspectacles2020vision",
        id: 2282,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "The King's Sunglasses",
        icon: "theking'ssunglasses2020vision",
        id: 2283,
        duration: 12,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Welding Goggles",
        icon: "weldinggoggles2020vision",
        id: 2284,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Flip Glasses",
        icon: "flipglasses2020vision",
        id: 2285,
        duration: 12,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Ski Goggles",
        icon: "skigoggles2020vision",
        id: 2286, //
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Theatre Binoculars",
        icon: "theatrebinoculars2020vision",
        id: 2287,
        duration: 12,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Joke Glasses",
        icon: "jokeglasses2020vision",
        id: 2288, //
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "3D Glasses",
        icon: "3dglasses2020vision",
        id: 2289,
        duration: 12,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Viewfinder",
        icon: "viewfinder2020vision",
        id: 2290,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "VR Goggles",
        icon: "vrgoggles2020vision",
        id: 2291,
        duration: 12,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Jeweler Loupe",
        icon: "jewelerloupe2020vision",
        id: 2292,
        duration: 12,
        lands_on: ["munzee"],
        alt_icons: ["jewelerloupe2020glasses"],
      },
      {
        name: "Aviator",
        icon: "aviator2020vision",
        id: 2293,
        duration: 12,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
        alt_icons: ["aviators2020vision"],
      },
      {
        name: "Summer Shades",
        icon: "summershades2020vision",
        id: 2294,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Party Glasses",
        icon: "partyglasses2020vision",
        id: 2295,
        duration: 12,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Broken Glasses",
        icon: "brokenglasses2020vision",
        id: 2296,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Emerald City Glasses",
        icon: "emeraldcityglasses2020vision",
        id: 2297,
        duration: 12,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Peace Glasses",
        icon: "peaceglasses2020vision",
        id: 2298,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Hunting Glasses",
        icon: "huntingglasses2020vision",
        id: 2299,
        duration: 12,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Cat-Eye Glasses",
        icon: "cat-eyeglasses2020vision",
        id: 2300,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Disguise Glasses",
        icon: "disguiseglasses2020vision",
        id: 2301,
        duration: 12,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Microscope Glasses",
        icon: "microscopeglasses2020vision",
        id: 2302,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Meme Glasses",
        icon: "memeglasses2020vision",
        id: 2303,
        duration: 12,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Glow in the Dark Glasses",
        icon: "glowinthedarkglasses2020vision",
        id: 2304,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Eclipse Glasses",
        icon: "eclipseglasses2020vision",
        id: 2305,
        duration: 12,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
    ],
  },
  {
    name: "Fr057y",
    id: "christmas2020",
    starts: "2020-12-01T00:00:00-05:00",
    ends: "2020-12-31T23:59:00-05:00",
    pobs: [
      {
        name: "Fr057y",
        icon: "fr057y",
        id: 2743,
        lands_on: [],
      },
    ],
  },
  {
    name: "Christmas 2020",
    id: "christmas2020",
    starts: "2020-12-01T00:00:00-05:00",
    ends: "2020-12-31T23:59:00-05:00",
    pobs: [
      {
        name: "Cyborg Santa",
        icon: "cyborgsanta",
        id: 2695,
        lands_on: [],
      },
      {
        name: "Cybersaurus Rex",
        icon: "cybersaurusrex",
        id: 2696,
        lands_on: [],
      },
      {
        name: "GingerMech Man",
        icon: "gingermechman",
        id: 2703,
        lands_on: [],
      },
      {
        name: "GingerSnapped Man",
        icon: "gingersnappedman",
        id: 2730,
        lands_on: [],
      },
      {
        name: "ReinDroid",
        icon: "reindroid",
        id: 2735,
        lands_on: [],
      },
      {
        name: "Fleeting ReinDroid",
        icon: "fleetingreindroid",
        id: 2736,
        lands_on: [],
      },
      {
        name: "RUD01PH",
        icon: "rud01ph",
        id: 2737,
        lands_on: [],
      },
      {
        name: "Fleeting RUD01PH",
        icon: "fleetingrud01ph",
        id: 2738,
        lands_on: [],
      },
      {
        name: "31F",
        icon: "31f",
        id: 2739,
        lands_on: [],
      },
      {
        name: "KrampBot",
        icon: "krampbot",
        id: 2740,
        lands_on: [],
      },
    ],
  },
  {
    name: "Walla EggZ",
    id: "wallaeggz2020",
    starts: "2020-11-24T12:00:00-05:00",
    ends: "2020-12-15T23:59:00-05:00",
    specials: [
      {
        name: "Walla Joy Egg",
        icon: "wallajoyegg",
        id: "null_wallajoyegg",
        duration: 4,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "eggs",
          type => type.has_tag(TypeTags.TypeGaming) && type.state === TypeState.Virtual,
        ],
        hidden: [TypeHidden.Capture],
      },
      {
        name: "Walla Surprise Egg",
        icon: "wallasurpriseegg",
        id: "null_wallasurpriseegg",
        duration: 4,
        lands_on: [
          "munzee",
          "egg",
          type => type.has_tag(TypeTags.TypeGaming) && type.state === TypeState.Physical,
        ],
        hidden: [TypeHidden.Capture],
      },
      {
        name: "Chocolate Honeycombs",
        icon: "chocolatehoneycombs",
        id: 2714,
        duration: 4,
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
      {
        name: "Green Unicorn Toy Rocker",
        icon: "greenunicorntoyrocker",
        id: 2710,
        duration: 4,
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
      {
        name: "Mixed Candy",
        icon: "mixedcandy",
        id: 2709,
        duration: 4,
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
      {
        name: "Mini Bubbles",
        icon: "minibubbles",
        id: 2712,
        duration: 4,
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
      {
        name: "Popper Toy",
        icon: "poppertoy",
        id: 2707,
        duration: 4,
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
      {
        name: "Gummy WallaBees",
        icon: "gummywallabees",
        id: 2713,
        duration: 4,
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
      {
        name: "Plastic Dinosaur",
        icon: "plasticdinosaur",
        id: 2708,
        duration: 4,
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
      {
        name: "Pink Unicorn Toy Rocker",
        icon: "pinkunicorntoyrocker",
        id: 2715,
        duration: 4,
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
    ],
  },
  {
    name: "Christmas Critters",
    id: "christmascritter2020",
    starts: "2020-11-01T00:00:00-05:00",
    ends: "2020-12-31T23:59:00-05:00",
    pobs: [
      {
        name: "Baby Hippo",
        icon: "babyhippo",
        id: 2648,
        lands_on: ["treehouse", "munzee", "watermystery"],
      },
      {
        name: "Baby Alpaca",
        icon: "babyalpaca",
        id: 2649,
        lands_on: ["skyland", ":virtual", "electricmystery"],
      },
      {
        name: "Baby Reindeer",
        icon: "babyreindeer",
        id: 2647,
        lands_on: ["treehouse", "munzee", "icemystery", "skyland", ":virtual"],
      },
    ],
  },
  {
    name: "Deathly DeeZert",
    id: "halloween2020",
    starts: "2020-10-27T12:00:00-05:00",
    ends: "2020-11-15T23:59:00-05:00",
    specials: [
      {
        name: "Creepy Cauldron",
        icon: "creepycauldron",
        id: 2630,
        duration: 4,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "airmystery",
          "electricmystery",
          "flatrob",
          "flatmatt",
          "flatlou",
          "flathammock",
        ],
      },
      {
        name: "Pumpkin Pail",
        icon: "pumpkinpail",
        id: 2635,
        duration: 4,
        lands_on: [
          "munzee",
          "mystery",
          "firemystery",
          "earthmystery",
          "watermystery",
          "icemystery",
        ],
      },
      {
        name: "Mummy Macaron",
        icon: "mummymacaron",
        id: 2631,
        duration: 4,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "airmystery",
          "electricmystery",
          "flatrob",
          "flatmatt",
          "flatlou",
          "flathammock",
        ],
      },
      {
        name: "Pumpkin Pop",
        icon: "pumpkinpop",
        id: 2632,
        duration: 4,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "airmystery",
          "electricmystery",
          "flatrob",
          "flatmatt",
          "flatlou",
          "flathammock",
        ],
      },
      {
        name: "Blood Sucker",
        icon: "bloodsucker",
        id: 2633,
        duration: 4,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "airmystery",
          "electricmystery",
          "flatrob",
          "flatmatt",
          "flatlou",
          "flathammock",
        ],
      },
      {
        name: "Rock",
        icon: "rock",
        id: 2634,
        duration: 4,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "airmystery",
          "electricmystery",
          "flatrob",
          "flatmatt",
          "flatlou",
          "flathammock",
        ],
      },
      {
        name: "Bonbon Bat",
        icon: "bonbonbat",
        id: "null_bonbonbat",
        duration: 4,
        lands_on: [
          "munzee",
          "mystery",
          "firemystery",
          "earthmystery",
          "watermystery",
          "icemystery",
        ],
      },
      {
        name: "Frappenstein",
        icon: "frappenstein",
        id: 2637,
        duration: 4,
        lands_on: [
          "munzee",
          "mystery",
          "firemystery",
          "earthmystery",
          "watermystery",
          "icemystery",
        ],
      },
      {
        name: "Boo Brownie",
        icon: "boobrownie",
        id: 2638,
        duration: 4,
        lands_on: [
          "munzee",
          "mystery",
          "firemystery",
          "earthmystery",
          "watermystery",
          "icemystery",
        ],
      },
      {
        name: "Toothbrush",
        icon: "toothbrush",
        id: 2639,
        duration: 4,
        lands_on: [
          "munzee",
          "mystery",
          "firemystery",
          "earthmystery",
          "watermystery",
          "icemystery",
        ],
      },
    ],
  },
  {
    name: "Zeecret Agents",
    id: "zeecret2020",
    starts: "2020-10-08T12:00:00-05:00",
    ends: "2020-11-08T23:59:00-05:00",
    specials: [
      {
        name: "PINE Agent",
        icon: "pineagent",
        id: 2616,
        duration: 4,
        lands_on: [
          "munzee",
          "mystery",
          "earthmystery",
          type => type.has_tag(TypeTags.TypeVirtual),
          "selfdestructcard",
          "briefcase",
          "nightvisiongoggles",
          "treehouse",
          "skyland",
        ],
      },
      {
        name: "PEAR Agent",
        icon: "pearagent",
        id: 2615,
        duration: 4,
        lands_on: [
          "munzee",
          "mystery",
          "earthmystery",
          type => type.has_tag(TypeTags.TypeVirtual),
          "selfdestructcard",
          "briefcase",
          "nightvisiongoggles",
          "treehouse",
          "skyland",
        ],
      },
      {
        name: "Virtual Pineamite",
        icon: "virtualpineamite",
        id: 2614,
        duration: 4,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "selfdestructcard",
          "nightvisiongoggles",
        ],
      },
      {
        name: "Physical Pineamite",
        icon: "physicalpineamite",
        id: 2613,
        duration: 4,
        lands_on: ["munzee", "mystery", "earthmystery", "briefcase"],
      },
      {
        name: "Virtual Pear Bomb",
        icon: "virtualpearbomb",
        id: 2612,
        duration: 6,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "selfdestructcard",
          "nightvisiongoggles",
        ],
      },
      {
        name: "Physical Pear Bomb",
        icon: "physicalpearbomb",
        id: 2611,
        duration: 4,
        lands_on: ["munzee", "mystery", "earthmystery", "briefcase"],
      },
    ],
  },
  {
    name: "Bash from the Past",
    id: "bash2020",
    starts: "2020-09-21T14:30:00-05:00",
    ends: "2020-10-11T23:59:00-05:00",
    specials: [
      {
        name: "Beer Boot",
        icon: "oktoberfestbash-beerboot",
        id: 2594,
        duration: 6,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual), "airmystery", "electricmystery"],
      },
      {
        name: "Paint Pallette",
        icon: "artwalkbash-paintpalette",
        id: 2595,
        duration: 6,
        lands_on: [
          "munzee",
          "firemystery",
          "mystery",
          "icemystery",
          "watermystery",
          "earthmystery",
        ],
      },
      {
        name: "Yellow Rose",
        icon: "lonestarbash-yellowrose",
        id: 2596,
        duration: 6,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual), "airmystery", "electricmystery"],
      },
      {
        name: "Playing Cards",
        icon: "all-inbash-playingcards",
        id: 2597,
        duration: 6,
        lands_on: [
          "munzee",
          "firemystery",
          "mystery",
          "icemystery",
          "watermystery",
          "earthmystery",
        ],
      },
      {
        name: "Ghost",
        icon: "mh-boobash-ghost",
        id: 2598,
        duration: 6,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual), "airmystery", "electricmystery"],
      },
      {
        name: "Unicorn Stick Horse",
        icon: "medzeevaltimesbash-unicornstickhorse",
        id: 2599,
        duration: 6,
        lands_on: [
          "munzee",
          "firemystery",
          "mystery",
          "icemystery",
          "watermystery",
          "earthmystery",
        ],
      },
      {
        name: "ZeeOps Transmission",
        icon: "bashfromthepast-zeeopstransmission",
        id: 2600,
        duration: 6,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual), "airmystery", "electricmystery"],
      },
    ],
  },
  {
    name: "National Waffle Day",
    id: "waffleday2020",
    starts: "2020-08-24T12:00:00-05:00",
    ends: "2020-09-14T23:59:00-05:00",
    specials: [
      {
        name: "Belgian Waffle",
        icon: "belgianwaffle",
        id: 2583,
        duration: 4,
        lands_on: ["munzee", "calf", "cow", "milk", "piglet", "pig", "bacon"],
      },
      {
        name: "Stroopwafel",
        icon: "stroopwafel",
        id: 2584,
        duration: 4,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual), "chick", "chicken", "egg"],
      },
    ],
  },
  {
    name: "Camp Critters",
    id: "campcritter2020",
    starts: "2020-08-01T00:00:00-05:00",
    ends: "2020-09-31T23:59:00-05:00",
    pobs: [
      {
        name: "Baby Fox",
        icon: "babyfox",
        id: 2561,
        lands_on: ["skyland", ":virtual", "airmystery", "poicampground"],
        alt_icons: ["undefined"],
      },
      {
        name: "Baby Moose",
        icon: "babymoose",
        id: 2560,
        lands_on: ["treehouse", "munzee", "earthmystery", "watermystery"],
      },
      {
        name: "Baby Squirrel",
        icon: "babysquirrel",
        id: 2559,
        lands_on: [
          "treehouse",
          "munzee",
          "earthmystery",
          "watermystery",
          "skyland",
          ":virtual",
          "airmystery",
          "poicampground",
        ],
      },
      {
        name: "Bear Cub",
        icon: "bearcub",
        id: 2558,
        lands_on: [
          "treehouse",
          "munzee",
          "earthmystery",
          "watermystery",
          "skyland",
          ":virtual",
          "airmystery",
          "poicampground",
        ],
      },
    ],
  },
  {
    name: "Camp Counselors",
    id: "campcounselors2020",
    starts: "2020-07-29T12:00:00-05:00",
    ends: "2020-09-09T23:59:00-05:00",
    specials: [
      {
        name: "Counselor Cap-A-Lot",
        icon: "campcap-a-lotcounselor",
        id: 2565,
        duration: 6,
        lands_on: [
          "treehouse",
          "skyland",
          type => type.has_tag(TypeTags.TypeMystery),
          "munzee",
          type => type.has_tag(TypeTags.TypeVirtual),
        ],
      },
      {
        name: "Counselor QRantine",
        icon: "campqrantinecounselor",
        id: 2566,
        duration: 6,
        lands_on: [
          "treehouse",
          "skyland",
          type => type.has_tag(TypeTags.TypeMystery),
          "munzee",
          type => type.has_tag(TypeTags.TypeVirtual),
        ],
      },
      {
        name: "Counselor FrEEZ",
        icon: "campfreezcounselor",
        id: 2567,
        duration: 6,
        lands_on: [
          "treehouse",
          "skyland",
          type => type.has_tag(TypeTags.TypeMystery),
          "munzee",
          type => type.has_tag(TypeTags.TypeVirtual),
        ],
      },
      {
        name: "Counselor KenneZee",
        icon: "campkennezeecounselor",
        id: 2568,
        duration: 6,
        lands_on: [
          "treehouse",
          "skyland",
          type => type.has_tag(TypeTags.TypeMystery),
          "munzee",
          type => type.has_tag(TypeTags.TypeVirtual),
        ],
      },
    ],
  },
  {
    name: "Munzee's 9th Birthday",
    id: "munzeebirthday2020",
    starts: "2020-07-09T12:00:00-05:00",
    ends: "2020-08-09T23:59:00-05:00",
    specials: [
      {
        name: "Red Water Balloon",
        icon: "redwaterballoon",
        id: 2545,
        duration: 4,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Green Water Balloon",
        icon: "greenwaterballoon",
        id: 2546,
        duration: 4,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Blue Water Balloon",
        icon: "bluewaterballoon",
        id: 2547,
        duration: 4,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Yellow Water Balloon",
        icon: "yellowwaterballoon",
        id: 2548,
        duration: 4,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Camp Cap-A-Lot Flag",
        icon: "campcap-a-lotflag",
        id: 2549,
        duration: 2,
        lands_on: [
          "munzee",
          "earthmystery",
          "treehouse",
          "skyland",
          type => type.has_tag(TypeTags.TypeVirtual),
        ],
      },
      {
        name: "Camp QRantine Flag",
        icon: "campqrantineflag",
        id: 2550,
        duration: 2,
        lands_on: [
          "munzee",
          "earthmystery",
          "treehouse",
          "skyland",
          type => type.has_tag(TypeTags.TypeVirtual),
        ],
      },
      {
        name: "Camp FrEEZ Flag",
        icon: "campfreezflag",
        id: 2551,
        duration: 2,
        lands_on: [
          "munzee",
          "earthmystery",
          "treehouse",
          "skyland",
          type => type.has_tag(TypeTags.TypeVirtual),
        ],
      },
      {
        name: "Camp KenneZee Flag",
        icon: "campkennezeeflag",
        id: 2552,
        duration: 2,
        lands_on: [
          "munzee",
          "earthmystery",
          "treehouse",
          "skyland",
          type => type.has_tag(TypeTags.TypeVirtual),
        ],
      },
    ],
  },
  {
    name: "World Sushi Day Ingredients",
    id: "worldsushiday2020",
    starts: "2020-06-18T12:00:00-05:00",
    ends: "2020-07-08T23:59:00-05:00",
    specials: [
      {
        name: "Cucumber",
        icon: "cucumber",
        id: 2512,
        duration: 3,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "eggs",
          "farmer",
          "farmerandwife",
          "family",
        ],
      },
      {
        name: "Fried Egg",
        icon: "friedegg",
        id: 2513,
        duration: 4,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "eggs",
          "farmer",
          "farmerandwife",
          "family",
        ],
      },
      {
        name: "Puffer Fish",
        icon: "pufferfish",
        id: 2516,
        duration: 9,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "eggs",
          "farmer",
          "farmerandwife",
          "family",
        ],
      },
      {
        name: "Rice",
        icon: "rice",
        id: 2517,
        duration: 1,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "eggs",
          "farmer",
          "farmerandwife",
          "family",
        ],
      },
      {
        name: "Roe",
        icon: "roe",
        id: 2518,
        duration: 7,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "eggs",
          "farmer",
          "farmerandwife",
          "family",
        ],
      },
      {
        name: "Salmon",
        icon: "salmon",
        id: 2519,
        duration: 6,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "eggs",
          "farmer",
          "farmerandwife",
          "family",
        ],
      },
      {
        name: "Nori",
        icon: "nori",
        id: 2514,
        duration: 2,
        lands_on: ["watermystery", "mystery", "aquamarine", "longsword", "battleaxe"],
      },
      {
        name: "Prawn",
        icon: "prawn",
        id: 2515,
        duration: 5,
        lands_on: ["watermystery", "mystery", "aquamarine", "longsword", "battleaxe"],
      },
      {
        name: "Tuna",
        icon: "tuna",
        id: 2520,
        duration: 8,
        lands_on: ["watermystery", "mystery", "aquamarine", "longsword", "battleaxe"],
      },
    ],
  },
  {
    name: "World Sushi Day Masters",
    id: "worldsushidaymasters2020",
    starts: "2020-06-18T12:00:00-05:00",
    ends: "2020-07-08T23:59:00-05:00",
    specials: [
      {
        name: "Neko",
        icon: "sushimasterneko",
        id: 2521,
        duration: 6,
        lands_on: [
          "watermystery",
          "mystery",
          "aquamarine",
          "longsword",
          "battleaxe",
          type => type.has_tag(TypeTags.TypeVirtual),
          "eggs",
          "farmer",
          "farmerandwife",
          "family",
        ],
      },
      {
        name: "Kappa",
        icon: "sushimasterkappa",
        id: 2522,
        duration: 6,
        lands_on: [
          "watermystery",
          "mystery",
          "aquamarine",
          "longsword",
          "battleaxe",
          type => type.has_tag(TypeTags.TypeVirtual),
          "eggs",
          "farmer",
          "farmerandwife",
          "family",
        ],
      },
      {
        name: "Yurei",
        icon: "sushimasteryurei",
        id: 2523,
        duration: 6,
        lands_on: [
          "watermystery",
          "mystery",
          "aquamarine",
          "longsword",
          "battleaxe",
          type => type.has_tag(TypeTags.TypeVirtual),
          "eggs",
          "farmer",
          "farmerandwife",
          "family",
        ],
      },
    ],
  },
  {
    name: "Aquatic Baby Animals",
    id: "aquaticbabyanimals2020",
    starts: "2020-06-05T12:00:00-05:00",
    ends: "2020-06-21T23:59:00-05:00",
    specials: [
      {
        name: "Baby Narwhal",
        icon: "babynarwhal",
        id: 2508,
        duration: 6,
        lands_on: [
          type => type.has_tag(TypeTags.VirtualColourBlue),
          "seaweed",
          "fish",
          "shark",
          "canoe",
          "motorboat",
          "submarine",
          "planulalarva",
          "polyp",
        ],
      },
      {
        name: "Baby Penguin",
        icon: "babypenguin",
        id: 2509,
        duration: 5,
        lands_on: [
          type => type.has_tag(TypeTags.VirtualColourBlue),
          "seaweed",
          "fish",
          "shark",
          "canoe",
          "motorboat",
          "submarine",
          "planulalarva",
          "polyp",
        ],
      },
      {
        name: "Baby Crab",
        icon: "babycrab",
        id: 2507,
        duration: 4,
        lands_on: [
          "watermystery",
          "mystery",
          "aquamarine",
          "turtleegg",
          "turtlehatchling",
          "juvenileturtle",
        ],
      },
      {
        name: "Seal Pup",
        icon: "sealpup",
        id: 2510,
        duration: 3,
        lands_on: [
          type => type.has_tag(TypeTags.VirtualColourBlue),
          "seaweed",
          "fish",
          "shark",
          "canoe",
          "motorboat",
          "submarine",
          "planulalarva",
          "polyp",
        ],
      },
      {
        name: "Baby Shark",
        icon: "babyshark",
        id: 2511,
        duration: 2,
        lands_on: [
          type => type.has_tag(TypeTags.VirtualColourBlue),
          "seaweed",
          "fish",
          "shark",
          "canoe",
          "motorboat",
          "submarine",
          "planulalarva",
          "polyp",
        ],
      },
    ],
  },
  {
    name: "Hometown Heroes 2020",
    id: "hometownheroes2020",
    starts: "2020-05-18T12:00:00-05:00",
    ends: "2020-06-07T23:59:00-05:00",
    specials: [
      {
        name: "Stay Safe",
        icon: "staysafe",
        id: 2482,
        duration: 2,
        lands_on: ["virtual"],
      },
      {
        name: "Grocery Hero",
        icon: "groceryhero",
        id: 2485,
        duration: 4,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "First Responder Hero",
        icon: "firstresponderhero",
        id: 2487,
        duration: 4,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Healthcare Hero",
        icon: "healthcarehero",
        id: 2486,
        duration: 4,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Education Hero",
        icon: "educationhero",
        id: 2484,
        duration: 4,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Delivery Hero",
        icon: "deliveryhero",
        id: 2483,
        duration: 4,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Grocery Hero Mask",
        icon: "groceryheromask",
        id: 2490,
        duration: 6,
        lands_on: [
          "virtual_amethyst",
          "virtual_sapphire",
          "airmystery",
          "virtual_citrine",
          "virtual_onyx",
          "electricmystery",
          "skyland",
        ],
      },
      {
        name: "First Responder Hero Mask",
        icon: "firstresponderheromask",
        id: 2492,
        duration: 6,
        lands_on: [
          "virtual_amethyst",
          "virtual_sapphire",
          "airmystery",
          "virtual_citrine",
          "virtual_onyx",
          "electricmystery",
          "skyland",
        ],
      },
      {
        name: "Health Hero Mask",
        icon: "healthheromask",
        id: 2491,
        duration: 6,
        lands_on: [
          "virtual_amethyst",
          "virtual_sapphire",
          "airmystery",
          "virtual_citrine",
          "virtual_onyx",
          "electricmystery",
          "skyland",
        ],
      },
      {
        name: "Education Hero Mask",
        icon: "educationheromask",
        id: 2489,
        duration: 6,
        lands_on: [
          "virtual_amethyst",
          "virtual_sapphire",
          "airmystery",
          "virtual_citrine",
          "virtual_onyx",
          "electricmystery",
          "skyland",
        ],
      },
      {
        name: "Delivery Hero Mask",
        icon: "deliveryheromask",
        id: 2488,
        duration: 6,
        lands_on: [
          "virtual_amethyst",
          "virtual_sapphire",
          "airmystery",
          "virtual_citrine",
          "virtual_onyx",
          "electricmystery",
          "skyland",
        ],
      },
    ],
  },
  {
    name: "Baby Animals",
    id: "babyanimals2020",
    starts: "2020-05-01T00:00:00-05:00",
    ends: "2020-06-30T23:59:00-05:00",
    pobs: [
      {
        name: "Hedgehog",
        icon: "hedgehog",
        id: 2427,
        lands_on: [
          "skyland",
          "treehouse",
          "earthmystery",
          "icemystery",
          "flatlou",
          type =>
            type.has_tag(TypeTags.TypeVirtual) &&
            ![
              "virtual",
              "virtual_black",
              "virtual_timberwolf",
              "virtual_gray",
              "virtual_silver",
            ].includes(type.icon),
        ],
      },
      {
        name: "Polar Bear",
        icon: "polarbear",
        id: 2428,
        lands_on: [
          "skyland",
          "treehouse",
          "earthmystery",
          "icemystery",
          "flatlou",
          type =>
            type.has_tag(TypeTags.TypeVirtual) &&
            ![
              "virtual",
              "virtual_black",
              "virtual_timberwolf",
              "virtual_gray",
              "virtual_silver",
            ].includes(type.icon),
        ],
      },
      {
        name: "Owlet",
        icon: "owlet",
        id: 2429,
        lands_on: [
          "skyland",
          "treehouse",
          "virtual",
          "airmystery",
          "electricmystery",
          "flathammock",
        ],
      },
    ],
  },
  {
    name: "World Laughter Day 2020",
    id: "worldlaughterday2020",
    starts: "2020-05-01T10:00:00-05:00",
    ends: "2020-05-17T23:59:00-05:00",
    specials: [
      {
        name: "Bison Joke",
        icon: "bisonjoke",
        id: 2437,
        duration: 5.05,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Chilly Joke",
        icon: "chillyjoke",
        id: 2441,
        duration: 5.05,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Librarian Joke",
        icon: "librarianjoke",
        id: 2436,
        duration: 5.05,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Cyclist Joke",
        icon: "cyclistjoke",
        id: 2442,
        duration: 5.05,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Pirate Joke",
        icon: "piratejoke",
        id: 2435,
        duration: 5.05,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Dad Joke",
        icon: "dadjoke",
        id: 2439,
        duration: 5.05,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Unicorn Joke",
        icon: "unicornjoke",
        id: 2444,
        duration: 5.05,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Grape Joke",
        icon: "grapejoke",
        id: 2440,
        duration: 5.05,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Ninja Joke",
        icon: "ninjajoke",
        id: 2443,
        duration: 5.05,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Fishy Joke",
        icon: "fishyjoke",
        id: 2438,
        duration: 5.05,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
    ],
  },
  {
    name: "Petting Zoo 2020",
    id: "pettingzoo2020",
    starts: "2020-04-09T11:11:00-05:00",
    ends: "2020-04-30T23:59:00-05:00",
    specials: [
      {
        name: "Baby Fawn",
        icon: "babyfawn",
        id: 2417,
        duration: 1,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "electricmystery",
          "surprise",
          "virtual_onyx",
          "virtual_citrine",
        ],
      },
      {
        name: "Baby Tiger",
        icon: "babytiger",
        id: 2419,
        duration: 1,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "electricmystery",
          "surprise",
          "virtual_onyx",
          "virtual_citrine",
        ],
      },
      {
        name: "Baby Lamb",
        icon: "babylamb",
        id: 2418,
        duration: 1,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "electricmystery",
          "surprise",
          "virtual_onyx",
          "virtual_citrine",
        ],
      },
      {
        name: "Baby Chick",
        icon: "babychick",
        id: 2416,
        duration: 1,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "electricmystery",
          "surprise",
          "virtual_onyx",
          "virtual_citrine",
        ],
      },
      {
        name: "Baby Bunny",
        icon: "babybunny",
        id: 2415,
        duration: 1,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "electricmystery",
          "surprise",
          "virtual_onyx",
          "virtual_citrine",
        ],
      },
    ],
  },
  {
    name: "Lou Roll 2020",
    id: "louroll2020",
    starts: "2020-03-31T11:11:00-05:00",
    ends: "2020-04-13T23:11:00-05:00",
    specials: [
      {
        name: "Lou Roll",
        icon: "louroll",
        id: 2411,
        duration: 4,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual), "flatlou"],
      },
    ],
  },
  {
    name: "Rainbow Trail 2020",
    id: "rainbowtrail2020",
    starts: "2020-03-17T13:00:00-05:00",
    ends: "2020-03-31T23:59:00-05:00",
    specials: [
      {
        name: "Rainbow Trail",
        icon: "rainbowtrail",
        id: 2394,
        duration: 7,
        lands_on: ["munzee", "shamrock", "earthmystery"],
        meta: {
          scatterer_radius: 1000,
          scatterer_types: [2395, 2396, 2397, 2398, 2399, 2400, 2401],
          scatterer_min: 1,
          scatterer_max: 3,
        },
      },
    ],
    types: [
      {
        name: "Red ZED",
        icon: "redzed",
        id: 2395,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 1,
        },
      },
      {
        name: "Orange ZED",
        icon: "orangezed",
        id: 2396,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 1,
        },
      },
      {
        name: "Yellow ZED",
        icon: "yellowzed",
        id: 2397,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 1,
        },
      },
      {
        name: "Green ZED",
        icon: "greenzed",
        id: 2398,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 1,
        },
      },
      {
        name: "Blue ZED",
        icon: "bluezed",
        id: 2399,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 1,
        },
      },
      {
        name: "Indigo ZED",
        icon: "indigozed",
        id: 2400,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 1,
        },
      },
      {
        name: "Violet ZED",
        icon: "violetzed",
        id: 2401,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 1,
        },
      },
    ],
  },
  {
    name: "Flat Day the 13th pt.3 2020",
    id: "flatdaythe13thpt.32020",
    starts: "2020-03-12T13:00:00-05:00",
    ends: "2020-03-17T13:00:00-05:00",
    specials: [
      {
        name: "THE RETURN",
        icon: "thereturn",
        id: 2393,
        duration: 6,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "Leap Day 2020",
    id: "leapday2020",
    starts: "2020-02-28T12:00:00-06:00",
    ends: "2020-03-03T10:00:00-06:00",
    specials: [
      {
        name: "H.Zee. Wells’ Time Machine",
        icon: "h.zee.wells'timemachine",
        id: 2363,
        duration: 4,
        lands_on: ["munzee", "premium", "mace", "mystery"],
      },
      {
        name: "Zeeloreon Time Traveler",
        icon: "zeeloreontimetraveler",
        id: 2364,
        duration: 4,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "TARDY Time Traveler",
        icon: "tardytimetraveler",
        id: 2365,
        duration: 4,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
    ],
  },
  {
    name: "Boomerangs 2020",
    id: "boomerangs2020",
    starts: "2020-01-24T10:00:00-06:00",
    ends: "2020-02-08T23:59:00-06:00",
    specials: [
      {
        name: "Coral Catcher Boomerang",
        icon: "coralcatcherboomerang",
        id: 2346,
        duration: 6,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual), "airmystery"],
      },
      {
        name: "Sunsetter Boomerang",
        icon: "sunsetterboomerang",
        id: 2345,
        duration: 6,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual), "airmystery"],
      },
      {
        name: "Parting Sea Boomerang",
        icon: "partingseaboomerang",
        id: 2344,
        duration: 6,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual), "airmystery"],
      },
      {
        name: "Great Dividing Boomerang",
        icon: "greatdividingboomerang",
        id: 2343,
        duration: 6,
        lands_on: ["munzee", "earthmystery"],
      },
      {
        name: "Country Crawler Boomerang",
        icon: "countrycrawlerboomerang",
        id: 2342,
        duration: 6,
        lands_on: ["munzee", "earthmystery"],
      },
      {
        name: "Root Runner Boomerang",
        icon: "rootrunnerboomerang",
        id: 2341,
        duration: 6,
        lands_on: ["munzee", "earthmystery"],
      },
    ],
  },
];

export default s2020;
