import { SeasonalCategory } from ".";
import { TypeHidden, TypeState, TypeTags } from "../../munzee";

const s2021: SeasonalCategory[] = [
  {
    name: "World Bicycle Day 2021",
    id: "worldbicycleday2021",
    starts: "2021-06-02T12:00:00-05:00",
    ends: "2021-06-17T23:59:00-05:00",
    pobs: [
      {
        name: "Champion Chopper",
        icon: "championchopper",
        id: "null_championchopper",
        lands_on: ["munzee", "shamrock", "firemystery", "pinkdiamond", "tractor"],
      },
      {
        name: "Unicorn Unicycle",
        icon: "unicornunicycle",
        id: "null_unicornunicycle",
        lands_on: ["munzee", "shamrock", "firemystery", "pinkdiamond", "tractor"],
      },
      {
        name: "Toy Trike",
        icon: "toytrike",
        id: "null_toytrike",
        lands_on: [
          i => i.has_tag(TypeTags.TypeVirtual),
          "flatlou",
          "poitransportation",
          i => i.meta.evolution_base === "firstwheel",
        ],
      },
      {
        name: "Bicentennial Bicycle",
        icon: "bicentennialbicycle",
        id: "null_bicentennialbicycle",
        lands_on: [
          i => i.has_tag(TypeTags.TypeVirtual),
          "flatlou",
          "poitransportation",
          i => i.meta.evolution_base === "firstwheel",
        ],
      },
    ],
  },
  {
    name: "Baby Panda",
    id: "babypanda2021",
    starts: "2021-05-21T12:00:00-05:00",
    ends: "2021-07-20T23:59:00-05:00",
    pobs: [
      {
        name: "Baby Panda",
        icon: "babypanda",
        id: "null_babypanda",
        lands_on: [],
      },
      {
        name: "Albino Baby Panda",
        icon: "albinobabypanda",
        id: "null_albinobabypanda",
        lands_on: [],
      },
    ],
  },
  {
    name: "Lost Socks",
    id: "lostsocks2021",
    starts: "2021-05-03T12:00:00-05:00",
    ends: "2021-05-31T23:59:00-05:00",
    specials: [
      {
        name: "Left Ankle Sock",
        icon: "leftanklesock",
        id: "null_leftanklesock",
        lands_on: [
          "munzee",
          "mystery",
          "urbanfit",
          i => i.has_tag(TypeTags.TypeGaming) && i.state === TypeState.Physical,
          i => i.has_tag(TypeTags.TypeMysteryElemental) && i.state === TypeState.Physical,
        ],
      },
      {
        name: "Left Argyle Sock",
        icon: "leftargylesock",
        id: "null_leftargylesock",
        lands_on: [
          "munzee",
          "mystery",
          "urbanfit",
          i => i.has_tag(TypeTags.TypeGaming) && i.state === TypeState.Physical,
          i => i.has_tag(TypeTags.TypeMysteryElemental) && i.state === TypeState.Physical,
        ],
      },
      {
        name: "Left Hole-y Sock",
        icon: "lefthole-ysock",
        id: "null_lefthole-ysock",
        lands_on: [
          "munzee",
          "mystery",
          "urbanfit",
          i => i.has_tag(TypeTags.TypeGaming) && i.state === TypeState.Physical,
          i => i.has_tag(TypeTags.TypeMysteryElemental) && i.state === TypeState.Physical,
        ],
      },
      {
        name: "Left Honeycomb Sock",
        icon: "lefthoneycombsock",
        id: "null_lefthoneycombsock",
        lands_on: [
          "munzee",
          "mystery",
          "urbanfit",
          i => i.has_tag(TypeTags.TypeGaming) && i.state === TypeState.Physical,
          i => i.has_tag(TypeTags.TypeMysteryElemental) && i.state === TypeState.Physical,
        ],
      },
      {
        name: "Left Striped Sock",
        icon: "leftstripedsock",
        id: "null_leftstripedsock",
        lands_on: [
          "munzee",
          "mystery",
          "urbanfit",
          i => i.has_tag(TypeTags.TypeGaming) && i.state === TypeState.Physical,
          i => i.has_tag(TypeTags.TypeMysteryElemental) && i.state === TypeState.Physical,
        ],
      },
      {
        name: "Left Toe Sock",
        icon: "lefttoesock",
        id: "null_lefttoesock",
        lands_on: [
          "munzee",
          "mystery",
          "urbanfit",
          i => i.has_tag(TypeTags.TypeGaming) && i.state === TypeState.Physical,
          i => i.has_tag(TypeTags.TypeMysteryElemental) && i.state === TypeState.Physical,
        ],
      },
      {
        name: "Left Tube Sock",
        icon: "lefttubesock",
        id: "null_lefttubesock",
        lands_on: [
          "munzee",
          "mystery",
          "urbanfit",
          i => i.has_tag(TypeTags.TypeGaming) && i.state === TypeState.Physical,
          i => i.has_tag(TypeTags.TypeMysteryElemental) && i.state === TypeState.Physical,
        ],
      },
      {
        name: "Left Unicorn Sock",
        icon: "leftunicornsock",
        id: "null_leftunicornsock",
        lands_on: [
          "munzee",
          "mystery",
          "urbanfit",
          i => i.has_tag(TypeTags.TypeGaming) && i.state === TypeState.Physical,
          i => i.has_tag(TypeTags.TypeMysteryElemental) && i.state === TypeState.Physical,
        ],
      },
      {
        name: "Right Ankle Sock",
        icon: "rightanklesock",
        id: "null_rightanklesock",
        lands_on: [
          i => i.has_tag(TypeTags.TypeVirtual),
          "poisports",
          i => i.has_tag(TypeTags.TypeMysteryElemental) && i.state === TypeState.Physical,
          "farmer",
          "farmerandwife",
          "family",
          "pottedplant",
          "garden",
          "field",
        ],
      },
      {
        name: "Right Argyle Sock",
        icon: "rightargylesock",
        id: "null_rightargylesock",
        lands_on: [
          i => i.has_tag(TypeTags.TypeVirtual),
          "poisports",
          i => i.has_tag(TypeTags.TypeMysteryElemental) && i.state === TypeState.Physical,
          "farmer",
          "farmerandwife",
          "family",
          "pottedplant",
          "garden",
          "field",
        ],
      },
      {
        name: "Right Hole-y Sock",
        icon: "righthole-ysock",
        id: "null_righthole-ysock",
        lands_on: [
          i => i.has_tag(TypeTags.TypeVirtual),
          "poisports",
          i => i.has_tag(TypeTags.TypeMysteryElemental) && i.state === TypeState.Physical,
          "farmer",
          "farmerandwife",
          "family",
          "pottedplant",
          "garden",
          "field",
        ],
      },
      {
        name: "Right Honeycomb Sock",
        icon: "righthoneycombsock",
        id: "null_righthoneycombsock",
        lands_on: [
          i => i.has_tag(TypeTags.TypeVirtual),
          "poisports",
          i => i.has_tag(TypeTags.TypeMysteryElemental) && i.state === TypeState.Physical,
          "farmer",
          "farmerandwife",
          "family",
          "pottedplant",
          "garden",
          "field",
        ],
      },
      {
        name: "Right Striped Sock",
        icon: "rightstripedsock",
        id: "null_rightstripedsock",
        lands_on: [
          i => i.has_tag(TypeTags.TypeVirtual),
          "poisports",
          i => i.has_tag(TypeTags.TypeMysteryElemental) && i.state === TypeState.Physical,
          "farmer",
          "farmerandwife",
          "family",
          "pottedplant",
          "garden",
          "field",
        ],
      },
      {
        name: "Right Toe Sock",
        icon: "righttoesock",
        id: "null_righttoesock",
        lands_on: [
          i => i.has_tag(TypeTags.TypeVirtual),
          "poisports",
          i => i.has_tag(TypeTags.TypeMysteryElemental) && i.state === TypeState.Physical,
          "farmer",
          "farmerandwife",
          "family",
          "pottedplant",
          "garden",
          "field",
        ],
      },
      {
        name: "Right Tube Sock",
        icon: "righttubesock",
        id: "null_righttubesock",
        lands_on: [
          i => i.has_tag(TypeTags.TypeVirtual),
          "poisports",
          i => i.has_tag(TypeTags.TypeMysteryElemental) && i.state === TypeState.Physical,
          "farmer",
          "farmerandwife",
          "family",
          "pottedplant",
          "garden",
          "field",
        ],
      },
      {
        name: "Right Unicorn Sock",
        icon: "rightunicornsock",
        id: "null_rightunicornsock",
        lands_on: [
          i => i.has_tag(TypeTags.TypeVirtual),
          "poisports",
          i => i.has_tag(TypeTags.TypeMysteryElemental) && i.state === TypeState.Physical,
          "farmer",
          "farmerandwife",
          "family",
          "pottedplant",
          "garden",
          "field",
        ],
      },
    ],
  },
  {
    name: "Baby Animals",
    id: "babyanimals2021",
    starts: "2021-04-01T00:00:00-05:00",
    ends: "2021-05-31T23:59:00-05:00",
    pobs: [
      {
        name: "Doge Pup",
        icon: "dogepup",
        id: "null_dogepup",
        lands_on: [],
      },
      {
        name: "Itty Bitty Kitty",
        icon: "ittybittykitty",
        id: "null_ittybittykitty",
        lands_on: [],
      },
      {
        name: "Baby Monkey",
        icon: "babymonkey",
        id: "null_babymonkey",
        lands_on: [],
      },
    ],
  },
  {
    name: "April Fools",
    id: "aprilfools2021",
    starts: "2021-04-01T12:00:00-05:00",
    ends: "2021-04-30T23:59:00-05:00",
    specials: [
      {
        name: "Bag of Tricks",
        icon: "bagoftricks",
        id: "null_bagoftricks",
        lands_on: [],
      },
      {
        name: "Sack of Surprises",
        icon: "sackofsurprises",
        id: "null_sackofsurprises",
        lands_on: [],
      },
    ],
    types: [
      {
        name: "Squirting Flower",
        icon: "squirtingflower",
        id: "null_squirtingflower",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Sneezing Powder",
        icon: "sneezingpowder",
        id: "null_sneezingpowder",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Can of Snakes",
        icon: "canofsnakes",
        id: "null_canofsnakes",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Spider Gum",
        icon: "spidergum",
        id: "null_spidergum",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Whoopee Cushion",
        icon: "whoopeecushion",
        id: "null_whoopeecushion",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Buzzer Ring",
        icon: "buzzerring",
        id: "null_buzzerring",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
    ],
  },
  {
    name: "Jack in Zee Box",
    id: "jackinzeebox",
    starts: "2021-03-31T12:00:00-05:00",
    ends: "2021-05-11T23:59:00-05:00",
    pobs: [
      {
        name: "Jack in Zee Box",
        icon: "jackinzeebox",
        id: "null_jackinzeebox",
        lands_on: [],
      },
      {
        name: "Applejack in Zee Box",
        icon: "jackinzeebox-applejackinthebox",
        id: "null_applejackinthebox",
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
      {
        name: "Blast in Zee Box",
        icon: "jackinzeebox-blastinthebox",
        id: "null_blastinthebox",
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
      {
        name: "Boxing Glove",
        icon: "jackinzeebox-boxingglove",
        id: "null_jackinzeebox",
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
      {
        name: "Fire Prankster",
        icon: "jackinzeebox-fireprankster",
        id: "null_jackinzeebox-fireprankster",
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
      {
        name: "High Five",
        icon: "jackinzeebox-highfive",
        id: "null_jackinzeebox-highfive",
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
      {
        name: "Ice Prankster",
        icon: "jackinzeebox-iceprankster",
        id: "null_jackinzeebox-iceprankster",
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
      {
        name: "Prankster",
        icon: "jackinzeebox-prankster",
        id: "null_jackinzeebox-prankster",
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
      {
        name: "ROBblehead",
        icon: "jackinzeebox-robblehead",
        id: "null_jackinzeebox-robblehead",
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
      {
        name: "Unicorn",
        icon: "jackinzeebox-unicorn",
        id: "null_jackinzeebox-unicorn",
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
      {
        name: "Zack in The Box",
        icon: "jackinzeebox-zackinthebox",
        id: "null_jackinzeebox-zackinthebox",
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
    ],
  },
  {
    name: "Zee Folk",
    id: "zeefolk2020",
    starts: "2021-03-17T00:00:00-05:00",
    ends: "2021-03-31T23:59:00-05:00",
    specials: [
      {
        name: "Zee Folk",
        icon: "zeefolk",
        id: "null_zeefolk",
        lands_on: [],
      },
    ],
  },
  {
    name: "Women's History Month",
    id: "womenshistory2020",
    starts: "2021-02-25T12:00:00-05:00",
    ends: "2021-03-14T23:59:00-05:00",
    specials: [
      {
        name: "Amelia Earhart",
        icon: "ameliaearhart",
        id: "null_ameliaearhart",
        lands_on: ["munzee", "mystery"],
      },
      {
        name: "Frida Kahlo",
        icon: "fridakahlo",
        id: "null_fridakahlo",
        lands_on: [
          "munzee",
          type =>
            type.has_tag(TypeTags.EvolutionNature) &&
            ["roseseed", "tulipseed", "lilyseed"].includes(type.meta.evolution_base || ""),
        ],
      },
      {
        name: "Hedy Lamarr",
        icon: "hedylamarr",
        id: "null_hedylamarr",
        lands_on: [
          "munzee",
          type => type.has_tag(TypeTags.TypeJewel) && type.state === TypeState.Physical,
        ],
      },
      {
        name: "Maya Angelou",
        icon: "mayaangelou",
        id: "null_mayaangelou",
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual), "poilibrary", "surprise"],
      },
      {
        name: "Jane Goodall",
        icon: "janegoodall",
        id: "null_janegoodall",
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "poiwildlife",
          type => type.meta.evolution_base === "safaritruck",
        ],
      },
      {
        name: "Margaret Hamilton",
        icon: "margarethamilton",
        id: "null_margarethamilton",
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "poiuniqueattraction",
          "joystickvirtual",
        ],
      },
    ],
    types: [
      {
        name: "Flight Pin",
        icon: "flightpin",
        id: "null_flightpin",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Palette",
        icon: "palette",
        id: "null_palette",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Film Reel",
        icon: "filmreel",
        id: "null_filmreel",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Poem",
        icon: "poem",
        id: "null_poem",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Chimpanzee",
        icon: "chimpanzee",
        id: "null_chimpanzee",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Rocket",
        icon: "rocket",
        id: "null_rocket",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
    ],
  },
  {
    name: "Courier Critters",
    id: "couriercritters2020",
    starts: "2021-02-01T00:00:00-05:00",
    ends: "2021-04-31T23:59:00-05:00",
    pobs: [
      {
        name: "Courier Stork",
        icon: "courierstork",
        id: 2853,
        lands_on: [],
      },
      {
        name: "Courier Owl",
        icon: "courierowl",
        id: 2854,
        lands_on: [],
      },
      {
        name: "Courier Pigeon",
        icon: "courierpigeon",
        id: 2855,
        lands_on: [],
      },
    ],
  },
  {
    name: "Special Delivery Cupid",
    id: "specialdeliverycupid2021",
    starts: "2021-02-01T00:00:00-06:00",
    ends: "2021-02-28T23:59:00-06:00",
    pobs: [
      {
        name: "Special Delivery Cupid",
        icon: "specialdeliverycupid",
        id: 2851,
        duration: 5,
        lands_on: [
          "treehouse",
          "skyland",
          "munzee",
          "firemystery",
          "airmystery",
          "poipostoffice",
          type => type.has_tag(TypeTags.TypeVirtual),
          type => type.has_tag(TypeTags.TypeReseller),
          type => type.has_tag(TypeTags.TypeSeasonal),
        ],
      },
    ],
    types: [
      {
        name: "Heart Arrow",
        icon: "heartarrow",
        id: 2852,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
    ],
  },
  {
    name: "Buzzle Box",
    id: "buzzlebox2021",
    starts: "2021-01-29T00:00:00-06:00",
    ends: "2021-02-21T23:59:00-06:00",
    specials: [
      {
        name: "Buzzle Box",
        icon: "buzzlebox",
        id: 2856,
        duration: 6,
        lands_on: [
          "munzee",
          "joystick",
          type => type.has_tag(TypeTags.TypeMystery) && type.state === TypeState.Physical,
        ],
      },
    ],
    types: [
      {
        name: "Red Buzzle Piece 1",
        icon: "redbuzzlepiece1",
        id: 2857,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Red Buzzle Piece 2",
        icon: "redbuzzlepiece2",
        id: 2858,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Red Buzzle Piece 3",
        icon: "redbuzzlepiece3",
        id: 2859,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Red Buzzle Piece 4",
        icon: "redbuzzlepiece4",
        id: 2860,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Green Buzzle Piece 1",
        icon: "greenbuzzlepiece1",
        id: 2861,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Green Buzzle Piece 2",
        icon: "greenbuzzlepiece2",
        id: 2862,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Green Buzzle Piece 3",
        icon: "greenbuzzlepiece3",
        id: 2863,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Green Buzzle Piece 4",
        icon: "greenbuzzlepiece4",
        id: 2864,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Yellow Buzzle Piece 1",
        icon: "yellowbuzzlepiece1",
        id: 2865,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Yellow Buzzle Piece 2",
        icon: "yellowbuzzlepiece2",
        id: 2866,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Yellow Buzzle Piece 3",
        icon: "yellowbuzzlepiece3",
        id: 2867,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Yellow Buzzle Piece 4",
        icon: "yellowbuzzlepiece4",
        id: 2868,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
    ],
  },
  {
    name: "Hamilton Hamzee",
    id: "hamiltonhamzee2021",
    starts: "2021-01-21T00:00:00-06:00",
    ends: "2021-03-15T23:59:00-06:00",
    pobs: [
      {
        name: "Hamilton Hamzee",
        icon: "hamiltonhamzee",
        id: 2850,
        duration: 6,
        lands_on: [
          "treehouse",
          "munzee",
          "earthmystery",
          "icemystery",
          type => type.has_tag(TypeTags.TypeSeasonal),
        ],
      },
    ],
  },
  {
    name: "Garden Gnomes",
    id: "gnomes2021",
    starts: "2021-01-01T00:00:00-06:00",
    ends: "2021-12-31T23:59:00-06:00",
    pobs: [
      {
        name: "Garden Gnome",
        icon: "gardengnome",
        id: 2775,
        duration: 6,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual), "munzee"],
      },
      {
        name: "Ice Hockey Garden Gnome",
        icon: "icehockeygardengnome",
        id: 2776,
        duration: 6,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "munzee",
          "icemystery",
          "treehouse",
          "skyland",
        ],
      },
      {
        name: "Archery Garden Gnome",
        icon: "archerygardengnome",
        id: 2777,
        duration: 6,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "munzee",
          "crossbow",
          "treehouse",
          "skyland",
        ],
      },
      {
        name: "Basketball Garden Gnome",
        icon: "basketballgardengnome",
        id: 2778,
        duration: 6,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "munzee",
          "airmystery",
          "treehouse",
          "skyland",
        ],
      },
      {
        name: "Running Garden Gnome",
        icon: "runninggardengnome",
        id: 2779,
        duration: 6,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "munzee",
          "urbanfit",
          "treehouse",
          "skyland",
        ],
      },
      {
        name: "Aussie Explorer Garden Gnome",
        icon: "aussieexplorergardengnome",
        id: "null_aussieexplorergardengnome",
        duration: 6,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "munzee",
          type => type.has_tag(TypeTags.TypeReseller) && !type.has_tag(TypeTags.Scatter),
          "treehouse",
          "skyland",
        ],
      },
      {
        name: "Gold Miner Garden Gnome",
        icon: "goldminergardengnome",
        id: "null_goldminergardengnome",
        duration: 6,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "munzee",
          type => type.has_tag(TypeTags.TypeReseller) && !type.has_tag(TypeTags.Scatter),
          "treehouse",
          "skyland",
          "coin",
          "bagofcoins",
          "treasurechest",
        ],
      },
      {
        name: "Queen's Guardsman Garden Gnome",
        icon: "queen'sguardsmangardengnome",
        id: "null_queen'sguardsmangardengnome",
        duration: 6,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "munzee",
          type => type.has_tag(TypeTags.TypeReseller) && !type.has_tag(TypeTags.Scatter),
          "treehouse",
          "skyland",
        ],
      },
      {
        name: "Astronaut Garden Gnome",
        icon: "astronautgardengnome",
        id: "null_astronautgardengnome",
        duration: 6,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "munzee",
          type => type.has_tag(TypeTags.TypeReseller) && !type.has_tag(TypeTags.Scatter),
          "treehouse",
          "skyland",
        ],
      },
      {
        name: "Soccer Garden Gnome",
        icon: "soccergardengnome",
        id: "null_soccergardengnome",
        duration: 6,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "munzee",
          "virtualonyx",
          "treehouse",
          "skyland",
        ],
      },
      {
        name: "Skateboarding Garden Gnome",
        icon: "skateboardinggardengnome",
        id: "null_skateboardinggardengnome",
        duration: 6,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "munzee",
          "poiplaypark",
          "treehouse",
          "skyland",
        ],
      },
    ],
    types: [
      {
        name: "Gnome Hockey Helmet",
        icon: "gnomehockeyhelmet",
        id: 2802,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Gnome Archery Hood",
        icon: "gnomearcheryhood",
        id: 2803,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Gnome Noggin Net",
        icon: "gnomenogginnet",
        id: 2804,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Gnome Miner Hat",
        icon: "gnomeminerhat",
        id: "null_gnomeminerhat",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Gnome Explorer Hat",
        icon: "gnomeexplorerhat",
        id: "null_gnomeexplorerhat",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Gnome Bear Skin Hat",
        icon: "gnomebearskinhat",
        id: "null_gnomebearskinhat",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Gnome Astronaut Helmet",
        icon: "gnomeastronauthelmet",
        id: "null_gnomeastronauthelmet",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Gnome Headphones",
        icon: "gnomeheadphones",
        id: 2805,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Gnome Header Hat",
        icon: "gnomeheaderhat",
        id: 2806,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Gnome Heelflip Hat",
        icon: "gnomeheelfliphat",
        id: 2807,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
    ],
  },
];

export default s2021;
