import { TypeID, TypeState, TypeTags } from "../../munzee";
import flathosts from "./flats";

const mythhosts: {
  name: string;
  icon: string;
  id: TypeID;
  state: TypeState;
  hosts: TypeID[];
  tags?: TypeTags[];
}[] = [
  {
    name: "Unicorn Host",
    icon: "unicornhost",
    id: 506,
    state: TypeState.Physical,
    hosts: [505],
    tags: [TypeTags.BouncerHostMythOriginal],
  },
  {
    name: "Leprechaun Host",
    icon: "leprechaunhost",
    id: 509,
    state: TypeState.Physical,
    hosts: [508, 1646, 1647],
    tags: [TypeTags.BouncerHostMythOriginal],
  },
  {
    name: "Dragon Host",
    icon: "dragonhost",
    id: 574,
    state: TypeState.Physical,
    hosts: [573, 1874, 1875],
    tags: [TypeTags.BouncerHostMythOriginal],
  },
  {
    name: "Yeti Host",
    icon: "yetihost",
    id: 726,
    state: TypeState.Physical,
    hosts: [725],
    tags: [TypeTags.BouncerHostMythOriginal],
  },
  {
    name: "Faun Host",
    icon: "faunhost",
    id: 854,
    state: TypeState.Physical,
    hosts: [853.1997, 1998],
    tags: [TypeTags.BouncerHostMythClassical],
  },
  {
    name: "Hydra Host",
    icon: "hydrahost",
    id: 954,
    state: TypeState.Physical,
    hosts: [953, 2252, 2253],
    tags: [TypeTags.BouncerHostMythClassical],
  },
  {
    name: "Pegasus Host",
    icon: "pegasushost",
    id: 1101,
    state: TypeState.Virtual,
    hosts: [1100, 1995, 1996],
    tags: [TypeTags.BouncerHostMythClassical],
  },
  {
    name: "Cyclops Host",
    icon: "cyclopshost",
    id: 1169,
    state: TypeState.Physical,
    hosts: [1168],
    tags: [TypeTags.BouncerHostMythClassical],
  },
  {
    name: "Cyclops Virtual Host",
    icon: "cyclops_virtual_host",
    id: 1170,
    state: TypeState.Virtual,
    hosts: [1168],
    tags: [TypeTags.BouncerHostMythClassical],
  },
  {
    name: "Mermaid Host",
    icon: "mermaidhost",
    id: 1379,
    state: TypeState.Physical,
    hosts: [1378, 1648, 1649],
    tags: [TypeTags.BouncerHostMythMirror],
  },
  {
    name: "Fairy Host",
    icon: "fairyhost",
    id: 1545,
    state: TypeState.Physical,
    hosts: [1544],
    tags: [TypeTags.BouncerHostMythMirror],
  },
  {
    name: "Fairy Virtual Host",
    icon: "fairy_virtual_host",
    id: 1546,
    state: TypeState.Virtual,
    hosts: [1544],
    tags: [TypeTags.BouncerHostMythMirror],
  },
  {
    name: "Mermaid Virtual Host",
    icon: "mermaid_virtual_host",
    id: 1650,
    state: TypeState.Virtual,
    hosts: [1649],
    tags: [TypeTags.BouncerHostMythMirror],
  },
  {
    name: "Leprechaun Virtual Host",
    icon: "leprechaun_virtual_host",
    id: 1651,
    state: TypeState.Virtual,
    hosts: [1646, 1647],
    tags: [TypeTags.BouncerHostMythOriginal],
  },
  {
    name: "Banshee Host",
    icon: "bansheehost",
    id: 1828,
    state: TypeState.Physical,
    hosts: [1827, 2254, 2255],
    tags: [TypeTags.BouncerHostMythMirror],
  },
  {
    name: "Banshee Virtual Host",
    icon: "banshee_virtual_host",
    id: 1829,
    state: TypeState.Virtual,
    hosts: [1827, 2254, 2255],
    tags: [TypeTags.BouncerHostMythMirror],
  },
  {
    name: "Dragon Virtual Host",
    icon: "dragon_virtual_host",
    id: 1878,
    state: TypeState.Virtual,
    hosts: [1874, 1875],
    tags: [TypeTags.BouncerHostMythOriginal],
  },
  {
    name: "Pegasus Physical Host",
    icon: "pegasusphysicalhost",
    id: 1999,
    state: TypeState.Physical,
    hosts: [1995, 1996],
    tags: [TypeTags.BouncerHostMythClassical],
  },
  {
    name: "Faun Virtual Host",
    icon: "faunvirtualhost",
    id: 2000,
    state: TypeState.Virtual,
    hosts: [1997, 1998],
    tags: [TypeTags.BouncerHostMythClassical],
  },
  {
    name: "Nymph Host",
    icon: "nymphhost",
    id: 2119,
    state: TypeState.Physical,
    hosts: [2118],
    tags: [TypeTags.BouncerHostMythMirror],
  },
  {
    name: "Nymph Virtual Host",
    icon: "nymph_virtual_host",
    id: 2120,
    state: TypeState.Virtual,
    hosts: [2118],
    tags: [TypeTags.BouncerHostMythMirror],
  },
];

export default flathosts;
