import { TypeID, TypeMeta, TypeState, TypeTags } from "../../munzee";

const retired: {
  name: string;
  icon: string;
  id: TypeID;
  tags?: TypeTags[];
  lands_on: TypeID[];
  meta?: TypeMeta;
  duration?: number;
}[] = [
  {
    name: "Retired Unicorn",
    icon: "retiredunicorn",
    id: 1535,
    lands_on: ["munzee", "shamrock"],
    tags: [TypeTags.BouncerMyth, TypeTags.BouncerRetired],
  },
  {
    name: "Retired Leprechaun",
    icon: "retiredleprechaun",
    id: 1536,
    lands_on: ["munzee", "shamrock"],
    tags: [TypeTags.BouncerMyth, TypeTags.BouncerRetired],
  },
  {
    name: "Retired Dragon",
    icon: "retireddragon",
    id: 1537,
    lands_on: ["munzee", "firemystery"],
    tags: [TypeTags.BouncerMyth, TypeTags.BouncerRetired],
  },
  {
    name: "Retired Yeti",
    icon: "retiredyeti",
    id: 1538,
    lands_on: ["munzee", "icemystery"],
    tags: [TypeTags.BouncerMyth, TypeTags.BouncerRetired],
  },
  {
    name: "Retired Faun",
    icon: "retiredfaun",
    id: 1539,
    lands_on: ["munzee", "earthmystery"],
    tags: [TypeTags.BouncerMyth, TypeTags.BouncerRetired],
  },
  {
    name: "Retired Hydra",
    icon: "retiredhydra",
    id: 1540,
    lands_on: ["munzee", "watermystery"],
    tags: [TypeTags.BouncerMyth, TypeTags.BouncerRetired],
  },
  {
    name: "Retired Mermaid",
    icon: "retiredmermaid",
    id: 1541,
    lands_on: [
      "munzee",
      "watermystery",
      type => type.has_tag(TypeTags.TypeJewel) && type.state === TypeState.Physical,
    ],
    tags: [TypeTags.BouncerMyth, TypeTags.BouncerRetired],
  },
  {
    name: "Retired Pegasus",
    icon: "retiredpegasus",
    id: 1542,
    lands_on: [type => type.has_tag(TypeTags.TypeVirtual), "airmystery", "electricmystery"],
    tags: [TypeTags.BouncerMyth, TypeTags.BouncerRetired],
  },
  {
    name: "Retired Cyclops",
    icon: "retiredcyclops",
    id: 1543,
    lands_on: [type => type.has_tag(TypeTags.TypeJewel) && type.id !== 148],
    tags: [TypeTags.BouncerMyth, TypeTags.BouncerRetired],
  },
  {
    name: "Retired Fairy",
    icon: "retiredfairy",
    id: 2051,
    lands_on: ["munzee", "airmystery", "mystery"],
    tags: [TypeTags.BouncerMyth, TypeTags.BouncerRetired],
  },
  {
    name: "Retired Banshee",
    icon: "retiredbanshee",
    id: 2052,
    lands_on: [
      "munzee",
      "shamrock",
      "airmystery",
      type => type.has_tag(TypeTags.VirtualColourBlack),
      type => type.has_tag(TypeTags.VirtualColourGreen),
    ],
    tags: [TypeTags.BouncerMyth, TypeTags.BouncerRetired],
  },
  {
    name: "Zombie Tuli",
    icon: "zombietuli",
    id: 2053,
    lands_on: ["munzee", "firemystery"],
    duration: 6,
    tags: [TypeTags.BouncerPC, TypeTags.BouncerPCZombie, TypeTags.BouncerRetired],
  },
  {
    name: "Zombie Vesi",
    icon: "zombievesi",
    id: 2054,
    lands_on: ["munzee", "watermystery"],
    duration: 6,
    tags: [TypeTags.BouncerPC, TypeTags.BouncerPCZombie, TypeTags.BouncerRetired],
  },
  {
    name: "Zombie Muru",
    icon: "zombiemuru",
    id: 2055,
    lands_on: ["munzee", "earthmystery"],
    duration: 6,
    tags: [TypeTags.BouncerPC, TypeTags.BouncerPCZombie, TypeTags.BouncerRetired],
  },
  {
    name: "Zombie Elekter",
    icon: "zombieelekter",
    id: "null_zombieelekter",
    lands_on: ["skyland", type => type.has_tag(TypeTags.TypeVirtual), "electricmystery"],
    duration: 6,
    tags: [TypeTags.BouncerPC, TypeTags.BouncerPCZombie, TypeTags.BouncerRetired],
  },
  {
    name: "Zombie Puffle",
    icon: "zombiepuffle",
    id: "null_zombiepuffle",
    lands_on: ["skyland", type => type.has_tag(TypeTags.TypeVirtual), "airmystery"],
    duration: 6,
    tags: [TypeTags.BouncerPC, TypeTags.BouncerPCZombie, TypeTags.BouncerRetired],
  },
  {
    name: "Zombie Magnetus",
    icon: "zombiemagnetus",
    id: "null_zombiemagnetus",
    lands_on: [
      "skyland",
      "treehouse",
      "munzee",
      "airmystery",
      type => type.has_tag(TypeTags.VirtualColourBlue),
      type => type.has_tag(TypeTags.VirtualColourRed),
      "watermystery",
      "joystickvirtual",
      "joystick",
      "virtual_yellow",
      "virtual_goldenrod",
      "virtual_dandelion",
    ],
    duration: 6,
    tags: [TypeTags.BouncerPC, TypeTags.BouncerPCZombie, TypeTags.BouncerRetired],
  },
  {
    name: "Zombie Pimedus",
    icon: "zombiepimedus",
    id: "null_zombiepimedus",
    lands_on: [
      "skyland",
      "treehouse",
      "munzee",
      ":reseller",
      type => type.has_tag(TypeTags.TypeZodiacChinese),
      "virtual_sapphire",
      "briefcase",
      "thehammer",
      "crossbow",
      "catapult",
    ],
    duration: 6,
    tags: [TypeTags.BouncerPC, TypeTags.BouncerPCZombie, TypeTags.BouncerRetired],
  },
  {
    name: "Retired Nymph",
    icon: "retirednymph",
    id: "null_retirednymph",
    lands_on: [
      "skyland",
      "treehouse",
      "munzee",
      "earthmystery",
      type => type.has_tag(TypeTags.VirtualColourBrown),
      type => type.has_tag(TypeTags.VirtualColourBlack),
      type => type.has_tag(TypeTags.VirtualColourGreen),
    ],
    tags: [TypeTags.BouncerMyth, TypeTags.BouncerRetired],
  },
  {
    name: "Phantom Flat Rob",
    icon: "phantomflatrob",
    id: "null_phantomflatrob",
    lands_on: [],
    duration: 6,
    tags: [TypeTags.BouncerPC, TypeTags.BouncerFlatPhantom, TypeTags.BouncerRetired],
  },
  {
    name: "Phantom Flat Matt",
    icon: "phantomflatmatt",
    id: "null_phantomflatmatt",
    lands_on: [],
    duration: 6,
    tags: [TypeTags.BouncerPC, TypeTags.BouncerFlatPhantom, TypeTags.BouncerRetired],
  },
  {
    name: "Phantom Flat Lou",
    icon: "phantomflatlou",
    id: "null_phantomflatlou",
    lands_on: [],
    duration: 6,
    tags: [TypeTags.BouncerPC, TypeTags.BouncerFlatPhantom, TypeTags.BouncerRetired],
  },
];

export default retired;