import dayjs from "dayjs";
import utc from "dayjs/plugin/utc";
import mhq from "./components/dayjsmhq";
import timezone from "dayjs/plugin/timezone";
import duration from "dayjs/plugin/duration";
import localizedFormat from "dayjs/plugin/localizedFormat";
dayjs.extend(utc);
dayjs.extend(mhq);
dayjs.extend(timezone);
dayjs.extend(duration);
dayjs.extend(localizedFormat);